apiVersion: v1
kind: Service
metadata:
  name: chat-service
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: chat
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: moonsungkim/chat-service:21
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-mysql-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: chat-mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: chat-mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: chat-mysql-config-map
              key: mysql-user-username
        - name: KAFKA_SERVICE
          value: kafka-service
        - name: KAFKA_TOPIC_NAME
          value: kafka-chat
        resources:
          requests:
            cpu: "400m"
      serviceAccountName: chat-service-account

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70