apiVersion: v1
kind: Service
metadata:
  name: chat-mysql-service
  labels:
    app: chat-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: chat-mysql
    tier: chat-mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-mysql-pvc
  labels:
    app: chat-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-mysql-deployment
  labels:
    app: chat-mysql
spec:
  selector:
    matchLabels:
      app: chat-mysql
      tier: chat-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chat-mysql
        tier: chat-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: chat-mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: chat-mysql-config-map
              key: mysql-database-name
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-mysql-pass
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: chat-mysql-config-map
              key: mysql-user-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-mysql-pass
              key: mysql-user-password
        ports:
        - containerPort: 3306
          name: chat-mysql
        resources:
          requests:
            cpu: "400m"
        volumeMounts:
        - name: chat-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: chat-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: chat-mysql-pvc

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat-mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-mysql-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70