apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: moonsungkim/frontend-nextjs:14
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://34.16.48.178"
        - name: NEXT_PUBLIC_ADDRESS_API_URL
          value: "https://grpc-proxy-server-mkvo6j4wsq-du.a.run.app/"
        - name: NEXT_PUBLIC_SOCKE_API_URL
          value: "http://34.31.160.98/"

      serviceAccountName: frontend-service-account