apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  selector:
    app: matching
  ports:
    - port: 80
      targetPort: 8080
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment
  labels:
    app: matching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
      - name: matching
        image: moonsungkim/matching-service:7
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        env:
        - name: KAKAO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: matching-pass
              key: kakao-secret-key
      serviceAccountName: match-service-account