apiVersion: v1
kind: Service
metadata:
  name: mentoring-service
spec:
  selector:
    app: mentoring
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentoring-deployment
  labels:
    app: mentoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mentoring
  template:
    metadata:
      labels:
        app: mentoring
    spec:
      containers:
      - name: mentoring
        image: moonsungkim/mentoring-service:2
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mentoring-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mentoring-mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mentoring-mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mentoring-mysql-config-map
              key: mysql-user-username
        - name: KAFKA_SERVICE
          value: kafka-service
        - name: KAFKA_TOPIC_NAME
          value: kafka-mentoring
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: mentoring-pass
              key: s3-bucket-name
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mentoring-pass
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mentoring-pass
              key: s3-serect-key
      serviceAccountName: mentoring-service-account