apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - port: 80
      targetPort: 8080
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: lordofkangs/post-service:40
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: post-mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: post-mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: post-mysql-config-map
              key: mysql-user-username
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: post-pass
              key: s3-bucket-name
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: post-pass
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: post-pass
              key: s3-serect-key
        - name: KAKAO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: post-pass
              key: kakao-secret-key
      serviceAccountName: post-service-account