apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - port: 80
      targetPort: 8080
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: moonsungkim/profile-service:4
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: profile-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: profile-mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: profile-mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: profile-mysql-config-map
              key: mysql-user-username
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: profile-pass
              key: s3-bucket-name
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: profile-pass
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: profile-pass
              key: s3-serect-key
      serviceAccountName: profile-service-account