apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: auth-redis
spec:
  ports:
    - port: 6379
  selector:
    app: auth-redis
    tier: redis

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis
  template:
    metadata:
      labels:
        app: auth-redis
        tier: redis
    spec:
      containers:
      - name: auth-redis
        image: redis
        args: ["--appendonly", "yes"]
        ports:
          - name: auth-redis
            containerPort: 6379
        volumeMounts:
          - name: lv-storage
            mountPath: /data
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
      volumes:
        - name: lv-storage
          persistentVolumeClaim:
            claimName: redis-pvc