apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 8080
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: moonsungkim/auth-service
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: auth-config
            mountPath: /app/config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-mysql-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: auth-mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: auth-mysql-config-map
              key: mysql-user-username
        - name: REDIS_HOST
          value: redis-service # redis-service 명
      volumes:
      - name: auth-config
        configMap:
          name: auth-config
      serviceAccountName: auth-service-account