apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - port: 80
      targetPort: 8080
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: moonsungkim/post-service
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-mysql-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: post-mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: post-mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: post-mysql-config-map
              key: mysql-user-username
      serviceAccountName: post-service-account