apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: auth-redis
spec:
  ports:
    - port: 6379
  selector:
    app: auth-redis
    tier: redis
  
--- 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auth-redis-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: auth-redis-storage
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis
  template:
    metadata:
      labels:
        app: auth-redis
        tier: redis
    spec:
      containers:
      - name: auth-redis
        image: redis
        args: ["--appendonly", "yes"]
        ports:
          - name: auth-redis
            containerPort: 6379
        volumeMounts:
          - name: lv-storage
            mountPath: /data
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
      volumes:
        - name: lv-storage
          persistentVolumeClaim:
            claimName: redis-pvc